In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('train.csv')

In [4]:
for name in df.columns:
    print(df[name].unique())
  

[ 842 1021  563 ... 1139 1467  858]
[0 1]
[2.2 0.5 2.5 1.2 1.7 0.6 2.9 2.8 2.1 1.  0.9 1.1 2.6 1.4 1.6 2.7 1.3 2.3
 2.  1.8 3.  1.5 1.9 2.4 0.8 0.7]
[0 1]
[ 1  0  2 13  3  4  5  7 11 12 16  6 15  8  9 10 18 17 14 19]
[0 1]
[ 7 53 41 10 44 22 24  9 33 17 52 46 13 23 49 19 39 47 38  8 57 51 21  5
 60 61  6 11 50 34 20 27 42 40 64 14 63 43 16 48 12 55 36 30 45 29 58 25
  3 54 15 37 31 32  4 18  2 56 26 35 59 28 62]
[0.6 0.7 0.9 0.8 0.1 0.5 1.  0.3 0.4 0.2]
[188 136 145 131 141 164 139 187 174  93 182 177 159 198 185 196 121 101
  81 156 199 114 111 132 143  96 200  88 150 107 100 157 160 119  87 152
 166 110 118 162 127 109 102 104 148 180 128 134 144 168 155 165  80 138
 142  90 197 172 116  85 163 178 171 103  83 140 194 146 192 106 135 153
  89  82 130 189 181  99 184 195 108 133 179 147 137 190 176  84  97 124
 183 113  92  95 151 117  94 173 105 115  91 112 123 129 154 191 175  86
  98 125 126 158 170 161 193 169 120 149 186 122 167]
[2 3 5 6 1 8 4 7]
[ 2  6  9 14  7 10  0 15  1 18 1

In [5]:
X = df.drop('price_range', axis=1)
y = df['price_range']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)


DecisionTreeClassifier()

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
from sklearn.metrics import f1_score
print(f1_score(classifier.predict(X_test), y_test, average='macro'))

0.8441202114279887


In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[83  9  0  0]
 [11 87 12  0]
 [ 0 13 76  7]
 [ 0  0 11 91]]
              precision    recall  f1-score   support

           0       0.88      0.90      0.89        92
           1       0.80      0.79      0.79       110
           2       0.77      0.79      0.78        96
           3       0.93      0.89      0.91       102

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84      0.84       400

